--- # yum_repo.yml

- hosts: vps
  gather_facts: no
  tasks:
    - name: Add epel repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: Add remi repository
      yum_repository:
        name: remi
        description: REMI YUM repo
        baseurl: http://rpms.remirepo.net/enterprise/$releasever
